export const projects = [
    {
        title: 'Atrophy: Graveyard of My Fallen Heroes',
        img: '/img/atrophy.png',
        descrip: 'Interactive VR environment simulating the decay of the self.',
        categories: ['dev', 'design'],
    },
    {
        title: 'ML Hacks',
        img: '/img/mlhacks.png',
        categories: ['dev', 'design'],
        descrip: 'Website for ML Hacks, Bay Area\'s premier Machine Learning focused hackathon for female and nonbinary high school students.',
    },
    {
        title: 'Cero',
        img: '/img/cero.png',
        categories: ['dev', 'design'],
        date: 'June 2021',
        award: '1st Place @ Hydrangea Hacks',
        descrip: 'Adventure/platformer game developed with Javascript using the melonJS game engine—complete with original sprites, tilesets, and maps.',
    },
    {
        title: 'BLOOG',
        img: '/img/bloog.png',
        categories: ['dev', 'design'],
        date: 'May 2021',
        descrip: 'Knockoff Quizlet. Built with React/Redux/Firebase.',
    },
    {
        title: 'LineScape',
        img: '/img/linescape.png',
        categories: ['dev', 'design'],
        date: 'April 2021',
        award: 'Best Design @ Superposition V',
        descrip: 'SVG drawing tool that provides an interactive visual interface designed to simplify the process of creating line animations for websites.',
    },
    {
        title: 'Snowball',
        img: '/img/snowball.png',
        categories: ['dev', 'design'],
        date: 'Oct 2020',
        award: 'Best Overall Hack @ Creatica 2020',
        descrip: 'Crowdfunding Android app created to maximize the impact of individual donations by taking advantage of corporate matching programs.',
    },
    {
        title: '2048',
        img: '/img/2048.png',
        categories: ['dev', 'design'],
        date: 'July 2020',
        descrip: 'Browser-based version of the classic 2048 game built with Javascript and HTML/CSS to include original styling and various themes.',
    },
    {
        title: '',
        img: '/img/.png',
        categories: ['dev', 'design'],
        descrip: '',
    },
];

export const things = [
    {
      title: 'acryllic scene 2',
      img: '/img/things/acr-2.png',
      link: 'https://lilianzlettuce.github.io/ad417/',
      categories: ['dev', 'design'],
      descrip: 'Interactive VR environment simulating the decay of the self.',
    },
    {
      title: 'acryllic scene 3',
      img: '/img/things/acr-3.png',
      link: 'https://lilianzlettuce.github.io/ad417/',
      categories: ['dev', 'design'],
      descrip: 'Interactive VR environment simulating the decay of the self.',
    },
    {
      title: 'face 2',
      img: '/img/things/face-a1.png',
      link: 'https://lilianzlettuce.github.io/ad417/',
      categories: ['dev', 'design'],
      descrip: 'Interactive VR environment simulating the decay of the self.',
    },
    {
      title: 'hell plant 1',
      img: '/img/things/hellplant-face-1.png',
      link: 'https://lilianzlettuce.github.io/ad417/',
      categories: ['dev', 'design'],
      descrip: 'Interactive VR environment simulating the decay of the self.',
    },
    /*{
      title: 'hell plant 1',
      img: '/img/things/hellplant-1.png',
      link: 'https://lilianzlettuce.github.io/ad417/',
      categories: ['dev', 'design'],
      descrip: 'Interactive VR environment simulating the decay of the self.',
    },*/
    {
      title: 'hell plant 1',
      img: '/img/things/hellplant-5.png',
      link: 'https://lilianzlettuce.github.io/ad417/',
      categories: ['dev', 'design'],
      descrip: 'Interactive VR environment simulating the decay of the self.',
    },
    /*{
      title: 'hell plant 1',
      img: '/img/things/hellplant-3.png',
      link: 'https://lilianzlettuce.github.io/ad417/',
      categories: ['dev', 'design'],
      descrip: 'Interactive VR environment simulating the decay of the self.',
    },*/
    {
      title: 'face 1',
      img: '/img/things/face-b1.png',
      link: 'https://lilianzlettuce.github.io/ad417/',
      categories: ['dev', 'design'],
      descrip: 'Interactive VR environment simulating the decay of the self.',
    },
    {
      title: 'Potty Simulator 1000',
      img: '/img/things/ps-2.png',
      link: 'https://lilianzlettuce.github.io/ad417/',
      categories: ['dev', 'design'],
      descrip: 'Interactive VR environment simulating the decay of the self.',
    },
    {
      title: 'Potty Simulator 1000',
      img: '/img/things/ps-1.png',
      link: 'https://lilianzlettuce.github.io/ad417/',
      categories: ['dev', 'design'],
      descrip: 'Interactive VR environment simulating the decay of the self.',
    },
    {
      title: 'Atrophy - An Artificial World',
      img: '/img/things/purple3.png',
      link: 'https://lilianzlettuce.github.io/ad417/',
      categories: ['dev', 'design'],
      descrip: 'Interactive VR environment simulating the decay of the self.',
    },
    {
      title: 'Atrophy - An Artificial World',
      img: '/img/things/purple1.png',
      link: 'https://lilianzlettuce.github.io/ad417/',
      categories: ['dev', 'design'],
      descrip: 'Interactive VR environment simulating the decay of the self.',
    },
    /*{
      title: 'Atrophy - An Artificial World',
      img: '/img/things/purple4.png',
      link: 'https://lilianzlettuce.github.io/ad417/',
      categories: ['dev', 'design'],
      descrip: 'Interactive VR environment simulating the decay of the self.',
    },*/
    {
      title: 'Japan Street View',
      img: '/img/things/p3.png',
      link: 'https://lilianzlettuce.github.io/ad417/',
      categories: ['dev', 'design'],
      descrip: 'Interactive VR environment simulating the decay of the self.',
    },
    {
      title: 'Japan Street View - Shaded',
      img: '/img/things/japan1.png',
      link: 'https://lilianzlettuce.github.io/ad417/',
      categories: ['dev', 'design'],
      descrip: 'Interactive VR environment simulating the decay of the self.',
    },
    {
      title: 'Unity Experiments - Toiletception',
      img: '/img/things/p5.png',
      link: 'https://lilianzlettuce.github.io/ad417/',
      categories: ['dev', 'design'],
      descrip: 'Interactive VR environment simulating the decay of the self.',
    },
    {
      title: 'what yellow\'s supposed to look like',
      img: '/img/things/p2.png',
      link: 'https://lilianzlettuce.github.io/ad417/',
      categories: ['dev', 'design'],
      descrip: 'Interactive VR environment simulating the decay of the self.',
    },
    {
      title: '',
      img: '/img/things/eye/v2-yellow-red-2.png',
      link: 'https://lilianzlettuce.github.io/ad417',
      categories: ['dev', 'design'],
      descrip: 'Interactive VR environment simulating the decay of the self.',
    },
    {
      title: '',
      img: '/img/things/eye/rgby.png',
      link: 'https://lilianzlettuce.github.io/ad417',
      categories: ['dev', 'design'],
      descrip: 'Interactive VR environment simulating the decay of the self.',
    },
    {
      title: '',
      img: '/img/things/eye/v3-cym.png',
      link: 'https://lilianzlettuce.github.io/ad417',
      categories: ['dev', 'design'],
      descrip: 'Interactive VR environment simulating the decay of the self.',
    },
    {
      title: '',
      img: '/img/things/eye/v3-pastel-by.png',
      link: 'https://lilianzlettuce.github.io/ad417',
      categories: ['dev', 'design'],
      descrip: 'Interactive VR environment simulating the decay of the self.',
    },
    {
      title: '',
      img: '/img/things/eye/v3-py-2.png',
      link: 'https://lilianzlettuce.github.io/ad417',
      categories: ['dev', 'design'],
      descrip: 'Interactive VR environment simulating the decay of the self.',
    },
    {
        title: 'Saber - Golden',
        img: '/img/things/p1.png',
        link: 'https://lilianzlettuce.github.io/ad417/',
        categories: ['dev', 'design'],
        descrip: 'Interactive VR environment simulating the decay of the self.',
    },
    {
      title: 'Saber - Double Rainbow',
      img: '/img/things/double-rainbow.png',
      link: 'https://lilianzlettuce.github.io/ad417/',
      categories: ['dev', 'design'],
      descrip: 'Interactive VR environment simulating the decay of the self.',
    },
    {
      title: 'Leaf of Absence',
      img: '/img/things/laa-poster.png',
      link: 'https://lilianzlettuce.github.io/ad417/',
      categories: ['dev', 'design'],
      descrip: 'Interactive VR environment simulating the decay of the self.',
    },
    {
      title: 'Banana Model',
      img: '/img/things/banana-1.png',
      link: 'https://lilianzlettuce.github.io/ad417/',
      categories: ['dev', 'design'],
      descrip: 'Interactive VR environment simulating the decay of the self.',
    },
    {
      title: 'Tree Model',
      img: '/img/things/3d-tree-1.png',
      link: 'https://lilianzlettuce.github.io/ad417/',
      categories: ['dev', 'design'],
      descrip: 'Interactive VR environment simulating the decay of the self.',
    },
    {
      title: 'Lynn',
      img: '/img/things/lynn.png',
      link: 'https://lilianzlettuce.github.io/ad417/',
      categories: ['dev', 'design'],
      descrip: 'Interactive VR environment simulating the decay of the self.',
    },
    {
      title: 'Kinoko',
      img: '/img/things/kinoko.png',
      link: 'https://lilianzlettuce.github.io/ad417/',
      categories: ['dev', 'design'],
      descrip: 'Interactive VR environment simulating the decay of the self.',
    },
    {
      title: 'Shadow Boi Droy',
      img: '/img/things/droy.png',
      link: 'https://lilianzlettuce.github.io/ad417/',
      categories: ['dev', 'design'],
      descrip: 'Interactive VR environment simulating the decay of the self.',
    },
    {
      title: 'Shiloh',
      img: '/img/things/shiloh.png',
      link: 'https://lilianzlettuce.github.io/ad417/',
      categories: ['dev', 'design'],
      descrip: 'Interactive VR environment simulating the decay of the self.',
    },
    {
      title: 'Ren',
      img: '/img/things/ren-bg.png',
      link: 'https://lilianzlettuce.github.io/ad417/',
      categories: ['dev', 'design'],
      descrip: 'Interactive VR environment simulating the decay of the self.',
    },
];