export const things = [
  {
    title: 'Light-Space Modulator',
    img: '/img/things/acr-2.png',
    link: 'https://lilianzlettuce.github.io/ad417/light-space-modulator-on-crack',
    categories: ['dev', 'design'],
    descrip: 'A-Frame | Javascript | HTML/CSS',
  },
  {
    title: 'Light-Space Modulator',
    img: '/img/things/acr-3.png',
    link: 'https://lilianzlettuce.github.io/ad417/light-space-modulator-on-crack',
    categories: ['dev', 'design'],
    descrip: 'A-Frame | Javascript | HTML/CSS',
  },
  {
    title: 'face of egg',
    img: '/img/things/face-a1.png',
    link: '',
    categories: ['dev', 'design'],
    descrip: '',
  },
  {
    title: 'See No Evil - 3D',
    img: '/img/things/eye/3d-y4.png',
    link: '',
    categories: ['dev', 'design'],
    descrip: 'Blender',
  },
  {
    title: 'See No Evil - 3D',
    img: '/img/things/eye/3d-r1.png',
    link: '',
    categories: ['dev', 'design'],
    descrip: 'Blender',
  },
  {
    title: 'face of braddicus',
    img: '/img/things/face-b1.png',
    link: '',
    categories: ['dev', 'design'],
    descrip: '',
  },
  {
    title: 'Imaginary Plant',
    img: '/img/things/hellplant-face-1.png',
    link: 'https://lilianzlettuce.github.io/ad417/imaginary-plant',
    categories: ['dev', 'design'],
    descrip: 'Blender | A-Frame',
  },
  {
    title: 'Imaginary Plant',
    img: '/img/things/hellplant-5.png',
    link: 'https://lilianzlettuce.github.io/ad417/imaginary-plant',
    categories: ['dev', 'design'],
    descrip: 'Blender | A-Frame',
  },
  /*{
    title: 'hell plant 1',
    img: '/img/things/hellplant-3.png',
    link: 'https://lilianzlettuce.github.io/ad417/',
    categories: ['dev', 'design'],
    descrip: 'Interactive VR environment simulating the decay of the self.',
  },*/
  ////eye
  {
    title: 'Potty Simulator 2000',
    img: '/img/things/ps-2.png',
    link: 'https://lilianzlettuce.github.io/ad417/potty-simulator-2000',
    categories: ['dev', 'design'],
    descrip: 'Blender | A-Frame',
  },
  {
    title: 'Potty Simulator 2000',
    img: '/img/things/ps-1.png',
    link: 'https://lilianzlettuce.github.io/ad417/potty-simulator-2000',
    categories: ['dev', 'design'],
    descrip: 'Blender | A-Frame',
  },
  {
    title: 'Atrophy',
    img: '/img/things/purple3.png',
    link: 'https://lilianzlettuce.github.io/ad417/',
    categories: ['dev', 'design'],
    descrip: 'Javascript | A-Frame | HTML/CSS',
  },
  {
    title: 'Atrophy',
    img: '/img/things/purple1.png',
    link: 'https://lilianzlettuce.github.io/ad417/',
    categories: ['dev', 'design'],
    descrip: 'Javascript | A-Frame | HTML/CSS',
  },
  /*{
    title: 'Atrophy - An Artificial World',
    img: '/img/things/purple4.png',
    link: 'https://lilianzlettuce.github.io/ad417/',
    categories: ['dev', 'design'],
    descrip: 'Interactive VR environment simulating the decay of the self.',
  },*/
  {
    title: 'Japan Street View',
    img: '/img/things/p3.png',
    link: 'https://lilianzlettuce.github.io/ad417/',
    categories: ['dev', 'design'],
    descrip: 'Clip Studio Paint',
  },
  /*{
    title: 'Japan Street View - Shaded',
    img: '/img/things/japan1.png',
    link: 'https://lilianzlettuce.github.io/ad417/',
    categories: ['dev', 'design'],
    descrip: 'Interactive VR environment simulating the decay of the self.',
  },*/
  {
    title: 'Toiletception',
    img: '/img/things/p5.png',
    link: '',
    categories: ['dev', 'design'],
    descrip: 'Maya | Unity',
  },
  {
    title: 'See No Evil - 2D',
    img: '/img/things/p2.png',
    link: '',
    categories: ['dev', 'design'],
    descrip: 'Processing',
  },
  {
    title: 'See No Evil - 2D',
    img: '/img/things/eye/v2-yellow-red-2.png',
    link: '',
    categories: ['dev', 'design'],
    descrip: 'Processing',
  },
  {
    title: 'See No Evil - 2D',
    img: '/img/things/eye/rgby.png',
    link: '',
    categories: ['dev', 'design'],
    descrip: 'Processing',
  },
  {
    title: 'See No Evil - 2D',
    img: '/img/things/eye/v3-cym.png',
    link: '',
    categories: ['dev', 'design'],
    descrip: 'Processing',
  },
  {
    title: 'Saber - Double Rainbow',
    img: '/img/things/double-rainbow.png',
    link: '',
    categories: ['dev', 'design'],
    descrip: 'Clip Studio Paint',
  },
  {
    title: 'Leaf of Absence',
    img: '/img/things/laa-poster.png',
    link: '',
    categories: ['dev', 'design'],
    descrip: 'Clip Studio Paint',
  },
  {
    title: 'Banana Model',
    img: '/img/things/banana-1.png',
    link: '',
    categories: ['dev', 'design'],
    descrip: 'Maya',
  },
  /*{
    title: 'Tree Model',
    img: '/img/things/3d-tree-1.png',
    link: 'https://lilianzlettuce.github.io/ad417/',
    categories: ['dev', 'design'],
    descrip: 'Interactive VR environment simulating the decay of the self.',
  },*/
  {
    title: 'teeth',
    img: '/img/things/teeth1.png',
    link: '',
    categories: ['dev', 'design'],
    descrip: 'Autodesk Inventor',
  },
  {
    title: 'Snivy',
    img: '/img/things/snivy3.png',
    link: '',
    categories: ['dev', 'design'],
    descrip: 'Autodesk Inventor',
  },
  {
    title: 'Lynn',
    img: '/img/things/lynn.png',
    link: '',
    categories: ['dev', 'design'],
    descrip: 'Clip Studio Paint',
  },
  {
    title: 'Ren',
    img: '/img/things/ren-bg.png',
    link: '',
    categories: ['dev', 'design'],
    descrip: 'Clip Studio Paint',
  },
  {
    title: 'Shadow Boi Droy',
    img: '/img/things/droy.png',
    link: '',
    categories: ['dev', 'design'],
    descrip: 'Clip Studio Paint',
  },
  {
    title: 'Kinoko',
    img: '/img/things/kinoko.png',
    link: '',
    categories: ['dev', 'design'],
    descrip: 'Clip Studio Paint',
  },
  {
    title: 'Shiloh',
    img: '/img/things/shiloh.png',
    link: '',
    categories: ['dev', 'design'],
    descrip: 'Clip Studio Paint',
  }
];

export const things2D = [
  {
    title: 'See No Evil - 2D',
    img: '/img/things/eye/v3-cym.png',
    link: '',
    categories: ['dev', 'design'],
    descrip: 'Processing',
  },
  {
    title: 'See No Evil - 2D',
    img: '/img/things/eye/v3-py-2.png',
    link: '',
    categories: ['dev', 'design'],
    descrip: 'Processing',
  },
  {
    title: 'See No Evil - 2D',
    img: '/img/things/eye/v3-pastel-by.png',
    link: '',
    categories: ['dev', 'design'],
    descrip: 'Processing',
  },
  {
    title: '',
    img: '/img/things/eye/v2-yellow-red-2.png',
    link: 'https://lilianzlettuce.github.io/ad417',
    categories: ['dev', 'design'],
    descrip: 'Interactive VR environment simulating the decay of the self.',
  },
  {
    title: 'what yellow\'s supposed to look like',
    img: '/img/things/p2.png',
    link: 'https://lilianzlettuce.github.io/ad417/',
    categories: ['dev', 'design'],
    descrip: 'Interactive VR environment simulating the decay of the self.',
  },
  {
    title: '',
    img: '/img/things/eye/rgby.png',
    link: 'https://lilianzlettuce.github.io/ad417',
    categories: ['dev', 'design'],
    descrip: 'Interactive VR environment simulating the decay of the self.',
  },
  {
    title: 'Ren',
    img: '/img/things/ren-bg.png',
    link: 'https://lilianzlettuce.github.io/ad417/',
    categories: ['dev', 'design'],
    descrip: 'Interactive VR environment simulating the decay of the self.',
  },
  {
    title: 'Kinoko',
    img: '/img/things/kinoko.png',
    link: 'https://lilianzlettuce.github.io/ad417/',
    categories: ['dev', 'design'],
    descrip: 'Interactive VR environment simulating the decay of the self.',
  },
  {
    title: 'Lynn',
    img: '/img/things/lynn.png',
    link: 'https://lilianzlettuce.github.io/ad417/',
    categories: ['dev', 'design'],
    descrip: 'Interactive VR environment simulating the decay of the self.',
  },
  {
    title: 'Shiloh',
    img: '/img/things/shiloh.png',
    link: 'https://lilianzlettuce.github.io/ad417/',
    categories: ['dev', 'design'],
    descrip: 'Interactive VR environment simulating the decay of the self.',
  },
  {
    title: 'Japan Street View',
    img: '/img/things/p3.png',
    link: 'https://lilianzlettuce.github.io/ad417/',
    categories: ['dev', 'design'],
    descrip: 'Interactive VR environment simulating the decay of the self.',
  },
  {
    title: 'Japan Street View - Shaded',
    img: '/img/things/japan1.png',
    link: 'https://lilianzlettuce.github.io/ad417/',
    categories: ['dev', 'design'],
    descrip: 'Interactive VR environment simulating the decay of the self.',
  },
  {
    title: 'Shadow Boi Droy',
    img: '/img/things/droy.png',
    link: 'https://lilianzlettuce.github.io/ad417/',
    categories: ['dev', 'design'],
    descrip: 'Interactive VR environment simulating the decay of the self.',
  },
  {
      title: 'Saber - Golden',
      img: '/img/things/p1.png',
      link: 'https://lilianzlettuce.github.io/ad417/',
      categories: ['dev', 'design'],
      descrip: 'Interactive VR environment simulating the decay of the self.',
  },
  {
    title: 'Saber - Double Rainbow',
    img: '/img/things/double-rainbow.png',
    link: 'https://lilianzlettuce.github.io/ad417/',
    categories: ['dev', 'design'],
    descrip: 'Interactive VR environment simulating the decay of the self.',
  },
  {
    title: 'Leaf of Absence',
    img: '/img/things/laa-poster.png',
    link: 'https://lilianzlettuce.github.io/ad417/',
    categories: ['dev', 'design'],
    descrip: 'Interactive VR environment simulating the decay of the self.',
  },
];

export const things3D = [
  {
    title: 'Unity Experiments - Toiletception',
    img: '/img/things/p5.png',
    link: 'https://lilianzlettuce.github.io/ad417/',
    categories: ['dev', 'design'],
    descrip: 'Interactive VR environment simulating the decay of the self.',
  },
  /*{
    title: 'Tree Model',
    img: '/img/things/3d-tree-1.png',
    link: 'https://lilianzlettuce.github.io/ad417/',
    categories: ['dev', 'design'],
    descrip: 'Interactive VR environment simulating the decay of the self.',
  },*/
  {
    title: '3D eye',
    img: '/img/things/eye/3d-y4.png',
    link: 'https://lilianzlettuce.github.io/ad417/',
    categories: ['dev', 'design'],
    descrip: 'Interactive VR environment simulating the decay of the self.',
  },
  {
    title: '3D eye',
    img: '/img/things/eye/3d-r1.png',
    link: 'https://lilianzlettuce.github.io/ad417/',
    categories: ['dev', 'design'],
    descrip: 'Interactive VR environment simulating the decay of the self.',
  },
  {
    title: 'teeth',
    img: '/img/things/teeth1.png',
    link: 'https://lilianzlettuce.github.io/ad417/',
    categories: ['dev', 'design'],
    descrip: 'Interactive VR environment simulating the decay of the self.',
  },
  {
    title: 'snivy2',
    img: '/img/things/snivy3.png',
    link: 'https://lilianzlettuce.github.io/ad417/',
    categories: ['dev', 'design'],
    descrip: 'Interactive VR environment simulating the decay of the self.',
  },
  {
    title: 'Banana Model',
    img: '/img/things/banana-1.png',
    link: 'https://lilianzlettuce.github.io/ad417/',
    categories: ['dev', 'design'],
    descrip: 'Interactive VR environment simulating the decay of the self.',
  },
  {
    title: 'acryllic scene 2',
    img: '/img/things/acr-2.png',
    link: 'https://lilianzlettuce.github.io/ad417/',
    categories: ['dev', 'design'],
    descrip: 'Interactive VR environment simulating the decay of the self.',
  },
  {
    title: 'acryllic scene 3',
    img: '/img/things/acr-3.png',
    link: 'https://lilianzlettuce.github.io/ad417/',
    categories: ['dev', 'design'],
    descrip: 'Interactive VR environment simulating the decay of the self.',
  },
  {
    title: 'hell plant 1',
    img: '/img/things/hellplant-face-1.png',
    link: 'https://lilianzlettuce.github.io/ad417/',
    categories: ['dev', 'design'],
    descrip: 'Interactive VR environment simulating the decay of the self.',
  },
  {
    title: 'hell plant 1',
    img: '/img/things/hellplant-5.png',
    link: 'https://lilianzlettuce.github.io/ad417/',
    categories: ['dev', 'design'],
    descrip: 'Interactive VR environment simulating the decay of the self.',
  },
  {
    title: 'Potty Simulator 1000',
    img: '/img/things/ps-2.png',
    link: 'https://lilianzlettuce.github.io/ad417/',
    categories: ['dev', 'design'],
    descrip: 'Interactive VR environment simulating the decay of the self.',
  },
  {
    title: 'Potty Simulator 1000',
    img: '/img/things/ps-1.png',
    link: 'https://lilianzlettuce.github.io/ad417/',
    categories: ['dev', 'design'],
    descrip: 'Interactive VR environment simulating the decay of the self.',
  },
  {
    title: 'Atrophy - An Artificial World',
    img: '/img/things/purple3.png',
    link: 'https://lilianzlettuce.github.io/ad417/',
    categories: ['dev', 'design'],
    descrip: 'Interactive VR environment simulating the decay of the self.',
  },
  {
    title: 'Atrophy - An Artificial World',
    img: '/img/things/purple1.png',
    link: 'https://lilianzlettuce.github.io/ad417/',
    categories: ['dev', 'design'],
    descrip: 'Interactive VR environment simulating the decay of the self.',
  },
];

export const thingsInteractive = [
  {
    title: 'Atrophy - An Artificial World',
    img: '/img/things/purple3.png',
    link: 'https://lilianzlettuce.github.io/ad417/',
    categories: ['dev', 'design'],
    descrip: 'Interactive VR environment simulating the decay of the self.',
  },
  {
    title: 'acryllic scene 2',
    img: '/img/things/acr-2.png',
    link: 'https://lilianzlettuce.github.io/ad417/',
    categories: ['dev', 'design'],
    descrip: 'Interactive VR environment simulating the decay of the self.',
  },
  {
    title: 'acryllic scene 3',
    img: '/img/things/acr-3.png',
    link: 'https://lilianzlettuce.github.io/ad417/',
    categories: ['dev', 'design'],
    descrip: 'Interactive VR environment simulating the decay of the self.',
  },
  {
    title: 'face 2',
    img: '/img/things/face-a1.png',
    link: 'https://lilianzlettuce.github.io/ad417/',
    categories: ['dev', 'design'],
    descrip: 'Interactive VR environment simulating the decay of the self.',
  },
  {
    title: 'hell plant 1',
    img: '/img/things/hellplant-5.png',
    link: 'https://lilianzlettuce.github.io/ad417/',
    categories: ['dev', 'design'],
    descrip: 'Interactive VR environment simulating the decay of the self.',
  },
  {
    title: 'hell plant 1',
    img: '/img/things/hellplant-face-1.png',
    link: 'https://lilianzlettuce.github.io/ad417/',
    categories: ['dev', 'design'],
    descrip: 'Interactive VR environment simulating the decay of the self.',
  },
  {
    title: 'Potty Simulator 1000',
    img: '/img/things/ps-2.png',
    link: 'https://lilianzlettuce.github.io/ad417/',
    categories: ['dev', 'design'],
    descrip: 'Interactive VR environment simulating the decay of the self.',
  },
  {
    title: 'Potty Simulator 1000',
    img: '/img/things/ps-1.png',
    link: 'https://lilianzlettuce.github.io/ad417/',
    categories: ['dev', 'design'],
    descrip: 'Interactive VR environment simulating the decay of the self.',
  },
];